/*
  https://developer.mozilla.org/en-US/docs/Web/CSS/display
*/

export default {
  block: { display: 'block' },
  inline: { display: 'inline' },
  runIn: { display: 'run-in' },
  flow: { display: 'flow' },
  flowRoot: { display: 'flow-root' },
  table: { display: 'table' },
  flex: { display: 'flex' },
  grid: { display: 'grid' },
  ruby: { display: 'ruby' },
  subgrid: { display: 'subgrid' },
  blockFlow: { display: 'block flow' },
  blockFlowRoot: { display: 'block flow-root' },
  blockTable: { display: 'block table' },
  blockFlex: { display: 'block flex' },
  blockGrid: { display: 'block grid' },
  blockRuby: { display: 'block ruby' },
  blockSubgrid: { display: 'block subgrid' },
  inlineFlow: { display: 'inline flow' },
  inlineFlowRoot: { display: 'inline flow-root' },
  inlineTable: { display: 'inline-table' },
  inlineFlex: { display: 'inline-flex' },
  inlineGrid: { display: 'inline-grid' },
  inlineRuby: { display: 'inline ruby' },
  inlineSubgrid: { display: 'inline subgrid' },
  runInFlow: { display: 'run-in flow' },
  runInFlowRoot: { display: 'run-in flow-root' },
  runInTable: { display: 'run-in table' },
  runInFlex: { display: 'run-in flex' },
  runInGrid: { display: 'run-in grid' },
  runInRuby: { display: 'run-in ruby' },
  runInSubgrid: { display: 'run-in subgrid' },
  listItemBlockFlow: { display: 'list-item block flow' },
  listItemBlockFlowRoot: { display: 'list-item block flow-root' },
  listItemBlockTable: { display: 'list-item block table' },
  listItemBlockFlex: { display: 'list-item block flex' },
  listItemBlockGrid: { display: 'list-item block grid' },
  listItemBlockRuby: { display: 'list-item block ruby' },
  listItemBlockSubgrid: { display: 'list-item block subgrid' },
  listItemInlineFlow: { display: 'list-item inline flow' },
  listItemInlineFlowRoot: { display: 'list-item inline flow-root' },
  listItemInlineTable: { display: 'list-item inline table' },
  listItemInlineFlex: { display: 'list-item inline flex' },
  listItemInlineGrid: { display: 'list-item inline grid' },
  listItemInlineRuby: { display: 'list-item inline ruby' },
  listItemInlineSubgrid: { display: 'list-item inline subgrid' },
  listItemRunInFlow: { display: 'list-item run-in flow' },
  listItemRunInFlowRoot: { display: 'list-item run-in flow-root' },
  listItemRunInTable: { display: 'list-item run-in table' },
  listItemRunInFlex: { display: 'list-item run-in flex' },
  listItemRunInGrid: { display: 'list-item run-in grid' },
  listItemRunInRuby: { display: 'list-item run-in ruby' },
  listItemRunInSubgrid: { display: 'list-item run-in subgrid' },
  listItem: { display: 'list-item' },
  tableRowGroup: { display: 'table-row-group' },
  tableHeaderGroup: { display: 'table-header-group' },
  tableFooterGroup: { display: 'table-footer-group' },
  tableRow: { display: 'table-row' },
  tableCell: { display: 'table-cell' },
  tableColumnGroup: { display: 'table-column-group' },
  tableColumn: { display: 'table-column' },
  tableCaption: { display: 'table-caption' },
  rubyBase: { display: 'ruby-base' },
  rubyText: { display: 'ruby-text' },
  rubyBaseContainer: { display: 'ruby-base-container' },
  rubyTextContainer: { display: 'ruby-text-container' },
  contents: { display: 'contents' },
  none: { display: 'none' },
  inlineBlock: { display: 'inline-block' },
  inherit: { display: 'inherit' },
  initial: { display: 'initial' },
  unset: { display: 'unset' },
};
